image: php:7.3

stages:
    - test

cache:
    paths:
        - vendor/
  
before_script:
    - apt-get update -yqq
    - apt-get install git wget zip unzip -yqq
    - pecl install xdebug && docker-php-ext-enable xdebug
    # Install composer dependencies
    - wget https://composer.github.io/installer.sig -O - -q | tr -d '\n' > installer.sig
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php -r "if (hash_file('SHA384', 'composer-setup.php') === file_get_contents('installer.sig')) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php'); unlink('installer.sig');"
    - php composer.phar install

coverage:
    stage: test
    script:
        - ./vendor/bin/simple-phpunit --coverage-text

phpcs:
    stage: test
    script:
        - ./vendor/bin/phpcs --standard=PSR2 --exclude=Generic.Files.LineLength ./Entity/ ./Tests/