name: PHPUnit

on:
  push:
    branches: [ master, add-github-actions ]
  pull_request:
    branches: [ master, add-github-actions ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest

  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run test suite
        run: ./bin/phpunit --coverage-clover coverage.xml --colors=never

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v1.0.10
        with:
          name: Network Bundle Coverage Report
          file: coverage.xml
          flags: unittests
          env_vars: PHP
          fail_ci_if_error: false
